### ISSUE TITLE
 '.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nikunj10041998** [apigee/graphql-authz#5]

**Comment by nikunj10041998** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle graphql-authz@1.0.0~prebuild: graphql-authz@1.0.0
6 info lifecycle graphql-authz@1.0.0~build: graphql-authz@1.0.0
7 verbose lifecycle graphql-authz@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle graphql-authz@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\graphql-authz\node_modules\.bin;C:\Program Files\Java\jdk1.8.0_271\bin;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Nikunj\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Nikunj\AppData\Roaming\npm
9 verbose lifecycle graphql-authz@1.0.0~build: CWD: E:\graphql-authz
10 silly lifecycle graphql-authz@1.0.0~build: Args: [ '/d /s /c', './node_modules/rollup/bin/rollup -c' ]
11 silly lifecycle graphql-authz@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle graphql-authz@1.0.0~build: Failed to exec build script
13 verbose stack Error: graphql-authz@1.0.0 build: `./node_modules/rollup/bin/rollup -c`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:375:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:375:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid graphql-authz@1.0.0
15 verbose cwd E:\graphql-authz
16 verbose Windows_NT 10.0.10240
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.17.3
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error graphql-authz@1.0.0 build: `./node_modules/rollup/bin/rollup -c`
22 error Exit status 1
23 error Failed at the graphql-authz@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
